# Generated by Django 4.1.3 on 2022-11-30 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
